/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2018-05-12 10:59:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<title>闲货 - 湖工二手交易网</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/titleicon.ico\" media=\"screen\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/page_base.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<input id=\"cu\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<div id=\"top_bar\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"javascript:;\" id=\"addFav\">收藏本站</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"\" id=\"scanicon\">关注闲货</a></li>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t<li><a href=\"pages/feedback.jsp\">意见反馈</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a id=\"to_top\" href=\"javascript:topButton();\" title=\"返回顶部\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<nav class=\"header_nav\">\r\n");
      out.write("\t\t\t<div class=\"index_img\">\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"首页.jpg\" src=\"img/index_black.png\" />\r\n");
      out.write("\t\t\t\t\t<p>你有什么闲货呢?</p>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">首页</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"pages/publish.jsp\">发布二手</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"pages/mygs.jsp\">我的二手</a></li>\r\n");
      out.write("\t\t\t\t<li>|</li>\r\n");
      out.write("\t\t\t\t<li><a id=\"to-chat\" href=\"javascript:;\">聊一聊</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t<input class=\"search_in\" type=\"text\" placeholder=\"搜闲货\" />\r\n");
      out.write("\t\t\t\t<button class=\"search_btn\" onclick=\"search()\">搜索</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<div class=\"content_top\">\r\n");
      out.write("\t\t\t<nav class=\"content_nav\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">日常生活</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span><span>日用</span></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">鞋服配饰</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>女装</span>\r\n");
      out.write("\t\t\t\t\t\t<span>女鞋</span>\r\n");
      out.write("\t\t\t\t\t\t<span>配饰</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">闲置书籍</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>教材</span>\r\n");
      out.write("\t\t\t\t\t\t<span>小说</span>\r\n");
      out.write("\t\t\t\t\t\t<span>杂志</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">闲置数码</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>手机</span>\r\n");
      out.write("\t\t\t\t\t\t<span>电脑</span>\r\n");
      out.write("\t\t\t\t\t\t<span>电子配件</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">闲置箱包</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>男包</span>\r\n");
      out.write("\t\t\t\t\t\t<span>女包</span>\r\n");
      out.write("\t\t\t\t\t\t<span>旅行箱</span>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div class=\"scroll\">\r\n");
      out.write("\t\t\t\t<img class=\"atuo_img\" src=\"img/ad1.jpg\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"user_menu\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"menu_bars\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"pages/publish.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>发布闲货 <span class=\"icon\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>闲置换钱 快速出手</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"pages/mygs.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>我的闲货 <span class=\"icon\"></span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>查看闲货、个人资料</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content_bottom\">\r\n");
      out.write("\t\t\t<div class=\"column recent\">\r\n");
      out.write("\t\t\t\t<div class=\"column_title\">\r\n");
      out.write("\t\t\t\t\t<p>最新发布</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"column_info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"recent_img\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><img src=\"img/uheads/header_1.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><img src=\"img/uheads/header_2.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><img src=\"img/uheads/header_3.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><img src=\"img/uheads/header_4.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><img src=\"img/index_black.png\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><img src=\"img/header.jpg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"recent_text\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"pages/goodsinfo.jsp\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<p>[手机/数码] <a href=\"\">特价出售全新港行原装iPhone7plus</a> 03-08</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"column_title\">\r\n");
      out.write("\t\t\t\t\t<p>书籍资料<a class=\"more\" href=\"\">更多></a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"column_info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"obj_list\"  id=\"obj_list_3\">\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"column_title\">\r\n");
      out.write("\t\t\t\t\t<p>数码电子<a class=\"more\" href=\"\">更多></a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"column_info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"obj_list\"  id=\"obj_list_4\">\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"column_title\">\r\n");
      out.write("\t\t\t\t\t<p>鞋服配饰<a class=\"more\" href=\"\">更多></a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"column_info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"obj_list\" id=\"obj_list_2\">\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"column_title\">\r\n");
      out.write("\t\t\t\t\t<p>日常生活<a class=\"more\" href=\"\">更多></a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"column_info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"obj_list\" id=\"obj_list_1\">\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"column_title\">\r\n");
      out.write("\t\t\t\t\t<p>闲置箱包<a class=\"more\" href=\"\">更多></a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"column_info\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"obj_list\"  id=\"obj_list_5\">\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li>· &nbsp;&nbsp;&nbsp;<a href=\"\">特价出售全新港行原装iPhone7plus</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"clear: both;height: 10px;\"></div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"mokuai\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>关于我们</dt>\r\n");
      out.write("\t\t\t\t<dd><a href=\"pages/aboutus.jsp?id=0\">网站简介</a></dd>\r\n");
      out.write("\t\t\t\t<dd><a href=\"pages/aboutus.jsp?id=3\">服务协议</a></dd>\r\n");
      out.write("\t\t\t\t<dd><a href=\"pages/aboutus.jsp?id=2\">联系我们</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>帮助中心</dt>\r\n");
      out.write("\t\t\t\t<dd><a href=\"\">本站地图</a></dd>\r\n");
      out.write("\t\t\t\t<dd><a href=\"\">友情链接</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>商务合作</dt>\r\n");
      out.write("\t\t\t\t<dd><a href=\"pages/aboutus.jsp?id=1\">广告服务</a></dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"intro\">\r\n");
      out.write("\t\t\t<p>闲货精心打造、运营的一个为大学生服务、节约资源的大学生二手网。在网站上，学生可以交易使用过的生活物品、学习用品，学习资料等。网站以“绿色校园，绿色生活”为文化宗旨，为湖工学子们提供一个安全、实用、方便、绿色的大学生网站。</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t<p>本站所有信息均为用户自由发布，本站不对信息的真实性负任何责任，交易时请注意识别信息的真假如有网站内容侵害了您的权益请联系我们删除，举报电话：18274763360</p>\r\n");
      out.write("\t\t\t<p style=\"text-align: center;\">技术支持:陈白　 　联系QQ:29447637 　邮箱：29447637@qq.com</p>\r\n");
      out.write("\t\t\t<p style=\"text-align: center;\">Copyright &copy;2017 SecondHandMarket Corporation, All Rights Reserved</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/base_menu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/index.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /index.jsp(21,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.currentUser}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   \r\n");
        out.write("\t\t\t\t\t<li>你好，<a href=\"pages/user.jsp?op=login\">请登录</a></li>\r\n");
        out.write("\t\t\t\t\t<li><a href=\"pages/user.jsp?op=reg\">免费注册</a></li>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   \r\n");
        out.write("\t\t\t\t\t<li>你好，<a href=\"pages/mygs.jsp\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser.callName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</a></li>\r\n");
        out.write("\t\t\t\t\t<li><a href=\"User_exit\">退出</a></li>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f1.setParent(null);
    int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
    if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    // /index.jsp(101,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.currentUser}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   \r\n");
        out.write("\t\t\t\t\t\t<div class=\"user_head\"><img src=\"img/uheads/no_user.jpg\"></div>\r\n");
        out.write("\t\t\t\t\t\t<p class=\"foreword\">\r\n");
        out.write("\t\t\t\t\t\t\tHi!请先<a style=\"color: #42A0FF;\" href=\"pages/user.jsp?op=login\"> 登录 </a>!<br /> 登录享受更多功能!\r\n");
        out.write("\t\t\t\t\t\t\t<br/>\r\n");
        out.write("\t\t\t\t\t\t</p>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
    int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   \r\n");
        out.write("\t\t\t\t\t\t<div class=\"user_head\"><img src=\"img/uheads/header_");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser.headImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(".jpg\"></div>\r\n");
        out.write("\t\t\t\t\t\t<p class=\"foreword\">\r\n");
        out.write("\t\t\t\t\t\t\tHi! ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser.callName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<br/>\r\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fotherwise_005f1, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t</p>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f1);
    int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
    if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    // /index.jsp(114,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.currentUser.intro }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
    if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser.intro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
    int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<span style=\"color:#999999;\">请完善个人资料!</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
    return false;
  }
}
